### ISSUE TITLE
Map outdated

### ISSUE THREAD

**Issue by erisnuts** [philosophocat/moscow_metro#1]
Hi! Can you please add to the map following stations:
Очаково
Говорово
Боровское шоссе 
Мичуринский проспект 
Рассказовка 
Солнцево 
Новопеределкино 
Ул. Подбельского

**Comment by philosophocat** [comment]
Вы где-то уже используете эту карту? Если только планируете, то лучше поискать поддерживаемый вариант, если уже работает и всё-очень-плохо, то я постараюсь выделить время и добавить.

**Comment by erisnuts** [comment]
да, мы ее используем на одном из внутренних сервисов. все работает, только не хватает станций из списка. будем очень благодарны, если добавите.

**Comment by philosophocat** [comment]
Добавлю не раньше чем появятся на схемах метро. Пока и на яндекс.метро, и на схеме мосметро станции отсутствуют
