### ISSUE TITLE
add tutorial

### ISSUE THREAD

**Issue by erisnuts** [philosophocat/moscow_metro#2]
добрый день. судя по readme компонент больше не поддерживается. можно вас попросить составить некое руководство по поддержке и актуализации карты? я могу самостоятельно добавить новые станции. без вашей помощи разобраться будет очень сложно.

**Comment by philosophocat** [comment]
Не думал, что кто-то использует ещё. Раз такая история, поищу способ легко её актуализировать и поддерживать (например, с вашей помощью), но предварительный прогноз - отказ от зелёных маркеров при выделении. Они критичны для вас?

**Comment by erisnuts** [comment]
да, мы используем на продакшен-проекте. я готова помогать в актуализации и поддержке, особенно, если будет понятно, как это делается :)
я думаю, критично визуализировать выделение каким-либо образом, будут это зеленые маркеры или что-то другое - не важно, лишь бы было наглядно.

**Comment by philosophocat** [comment]
Появилась ветка 2.x: в ней новый набор зависимостей, добавил линтер, пересобрал список станций. Теперь можно брать карту с официального сайта (посмотреть путь в инспекторе) и просто закидывать её в папку src под именем map.svg. При сборке отдельный таск собирает воедино станции из .json-файла и svg-данные из карты. 
Нужно поправить имена на серой ветке наверху, добавить недостающие станции и проверить в разных браузерах. Ещё можно подумать об очистке, так как вместе с легендой и Москва-рекой карта сильно потяжелела. Собственно, присоединяйся, если будут вопросы - пиши сюда, этот тред пока не удаляю. По итогу сделаем ветку 2.x основной.
